### ISSUE TITLE
Migrate module to vox pupuli

### ISSUE THREAD

**Issue by alexjfisher** [voxpupuli/puppet-check_mk#1]
This module has been forked from https://github.com/gnubila-france/puppet-check_mk
This ticket is to track additional migration steps

- [x] Update metadata.json
- [x] Generate travis secret and add to plumbing
- [x] Add to modulesync_config
- [x] Perform initial modulesync
- [x] Make first Vox Pupuli release
- [x] Perform github label sync
- [ ] Create a Jira issue at https://tickets.puppetlabs.com and ask to deprecate the old module

**Comment by dhoppe** [comment]
We should add support for Ubuntu and drop CentOS / RHEL 5.

**Comment by zyronix** [comment]
@dhoppe I have been in contact with @alexjfisher about this module and already have a lot of work done.
To prevent double work, stuff that I have ready to implement:
- Updated the whole module to support check_mk 1.4+ (current module only works with check_mk <= 1.3
- Added support for Ubuntu (16.04, 18.04) Debian (8, 9) and RHEL (6,7)
- Fixed all the unittests

I am waiting for the initial modulesync.

**Comment by alexjfisher** [comment]
> We should add support for Ubuntu and drop CentOS / RHEL 5.

Perhaps open separate issues for improvements not directly related to getting the migration done?  Keep this specific ticket to the minimum needed to get a VP release out and on to the forge.

**Comment by alexjfisher** [comment]
https://tickets.puppetlabs.com/browse/FORGE-510
